version: '3.6'

services:

    atdome-csc:
        image: lsstts/at_dome_sim:3.9-0.5
        container_name: atdome-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
            - .setup.sh:/home/saluser/.setup.sh 
        entrypoint: ["/home/saluser/.setup.sh"]

